name: NASA PROJECT CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js version 22.7.0
        uses: actions/setup-node@v2
        with:
          node-version: '22.7.0'

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build --prefix client
